### ISSUE TITLE
"cpkg install tar" fails

### ISSUE THREAD

**Issue by sjakobi** [vmchale/cpkg#2]
```
$ cpkg install tar
cpkg: Data.Binary.Get.runGet at position 108592: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.6.0:Data.Binary.Get
```

```
$ cpkg --version
cpkg version: 0.2.3.3
```

**Comment by vmchale** [comment]
What happens if you run

```
cpkg nuke
```

beforehand? 

Unfortunately there is not good compatibility of package stores between versions :(

**Comment by sjakobi** [comment]
> cpkg nuke

Nice, that worked! :)

> Unfortunately there is not good compatibility of package stores between versions :(

Maybe rename it to `x.bkp` and start afresh when it fails to decode?!
